src/AppBundle/Entity/Beer.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Beer
 *
 * @ORM\Table(name="beer")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\BeerRepository")
 */
class Beer
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var Measurement[]
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Measurement", mappedBy="beer")
     */
    private $measurements;

    /**
     * Beer constructor.
     */
    public function __construct()
    {
        $this->measurements = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Beer
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return Measurement[]
     */
    public function getMeasurements()
    {
        return $this->measurements;
    }

    /**
     * @param Measurement[] $measurements
     */
    public function setMeasurements($measurements)
    {
        $this->measurements = $measurements;
    }


}

src/AppBundle/Entity/Measurement.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Measurement
 *
 * @ORM\Table(name="measurement")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MeasurementRepository")
 */
class Measurement
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var bool
     * @ORM\Column(name="is_active", type="boolean", options={"default": false})
     */
    private $isActive;

    /**
     * @var Beer
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Beer", inversedBy="measurements")
     */
    private $beer;

    /**
     * @var Device
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Device", inversedBy="measurements")
     */
    private $device;

    /**
     * @var LogData[]
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\LogData", mappedBy="measurement")
     */
    private $logData;

    /**
     * Measurement constructor.
     * @param Beer $beer
     */
    public function __construct(Beer $beer)
    {
        $this->beer = $beer;
        $this->logData = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Measurement
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return (bool)$this->isActive;
    }

    /**
     * @param bool $isActive
     */
    public function setIsActive(bool $isActive)
    {
        $this->isActive = $isActive;
    }

    /**
     * @return Beer
     */
    public function getBeer()
    {
        return $this->beer;
    }

    /**
     * @param Beer $beer
     */
    public function setBeer(Beer $beer)
    {
        $this->beer = $beer;
    }

    /**
     * @return Device
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * @param Device $device
     */
    public function setDevice(Device $device)
    {
        $this->device = $device;
    }

    /**
     * @return LogData[]
     */
    public function getLogData()
    {
        return $this->logData;
    }

    public function getLastLogdata()
    {
        return $this->logData->last();
    }

    /**
     * @param LogData[] $logData
     */
    public function setLogData($logData)
    {
        $this->logData = $logData;
    }
}

src/AppBundle/Form/BeerType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BeerType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, [
            'required' => true,
            'label' => 'labels.name'
        ]);
        $builder->add('save', SubmitType::class, [
            'label' => 'labels.save'
        ]);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Beer'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'beer';
    }


}

src/AppBundle/Controller/BeerController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Beer;
use AppBundle\Entity\Measurement;
use AppBundle\Form\BeerType;
use AppBundle\Form\MeasurementType;
use AppBundle\Repository\BeerRepository;
use AppBundle\Repository\MeasurementRepository;
use JMS\Serializer\Serializer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class DefaultController
 * @package AppBundle\Controller
 * @Route("beer")
 */
class BeerController extends Controller
{
    /**
     * @Route("/", name="beerList")
     */
    public function indexAction(Request $request)
    {
        $repository = $this->get(BeerRepository::class);
        $query = $repository->createQueryBuilder('b');

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1)
        );
        return $this->render('@App/beer/index.html.twig', [
            'pagination' => $pagination
        ]);
    }
    /**
     * @Route("/add", name="addBeer")
     */
    public function addAction(Request $request)
    {
        $beer = new Beer();
        $form = $this->createForm(BeerType::class, $beer);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $repository = $this->get(BeerRepository::class);
            $repository->persist($beer);

            $this->addFlash(
                'success',
                'Beer added'
            );

            return $this->redirectToRoute('showBeer', ['id'=> $beer->getId()]);
        }
        return $this->render('@App/beer/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/show/{id}", name="showBeer")
     */
    public function showAction(Beer $beer)
    {
        return $this->render('@App/beer/show.html.twig', [
            'beer' => $beer
        ]);
    }

    /**
     * @Route("/add-measurement/{id}", name="addMeasurementToBeer")
     */
    public function addMeasurement(Request $request, Beer $beer)
    {
        $measurement= new Measurement($beer);

        $form = $this->createForm(MeasurementType::class, $measurement);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $repository = $this->get(MeasurementRepository::class);
            $repository->persist($measurement);

            $this->addFlash(
                'success',
                'Measurement added'
            );

            return $this->redirectToRoute('showBeer', ['id'=> $beer->getId()]);
        }
        return $this->render('@App/beer/addMeasurement.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/get-measurements/{id}", name="getMeasurementsForBeer")
     */
    public function getMeasurementsAction(Beer $beer)
    {
        /** @var Serializer $serializer */
        $serializer = $this->get('jms_serializer');
        $result = $serializer->serialize($beer->getMeasurements(), 'json');
        return new JsonResponse($result, 200, [], true);
    }
}

src/AppBundle/Resources/views/beer/add.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="row x_title">
                    <div class="col-md-6">
                        <h3>{{ "beer.add.title"|trans }}</h3>
                    </div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/beer/addMeasurement.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="row x_title">
                    <div class="col-md-6">
                        <h3>{{ "beer.add.measurement"|trans }}</h3>
                    </div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/beer/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="row x_title">
                    <div class="col-md-6">
                        <h3>{{ "beer.pages.list"|trans }}</h3>
                    </div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <th>{{ "labels.name"|trans }}</th>
                            <th>{{ "labels.actions"|trans }}</th>
                        </thead>
                        <tbody>
                            {% for beer in pagination %}
                                <tr>
                                    <td>{{ beer.name }}</td>
                                    <td>
                                        <a href="{{ path('showBeer', {id: beer.id}) }}" class="btn btn-primary">
                                            <i class="fa fa-eye" aria-hidden="true"></i> {{ "labels.show"|trans }}
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pull-right navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/beer/show.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="title_left">
        <h3>{{ beer.name }} - {{ "beer.pages.show"|trans }}</h3>
    </div>
    <div class="row">
        {% for measurement in beer.measurements %}
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="x_panel tile fixed_height_320">
                    <div class="x_title">
                        <h2>{{ measurement.name }}</h2>
                        <div class="form-inline form-group pull-right">
                            <div class="input-group">
                                <input type="number" class="form-control" id="limit_{{ measurement.id }}" value="10">
                                <div class="input-group-addon">{{ "labels.minute"|trans }}</div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content text-center" >
                        {% if measurement.lastLogdata %}
                            <canvas id="mChart_{{ measurement.id }}" width="400" height="200"></canvas>
                            <div style="position: absolute; top:0; left: 40%">
                                <div class="row" id="lastValue_{{ measurement.id }}" style="font-size: 6em">{{ measurement.lastLogdata.value }}</div>
                                <div class="row" id="lastDate_{{ measurement.id }}">{{ measurement.lastLogdata.createDate|date('d-m-Y H:i:s') }}</div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

                <div class="row x_title">
                    <div class="col-md-6">

                    </div>
                </div>
                <div class="row">
                    <a href="{{ path('addMeasurementToBeer', {id: beer.id}) }}" class="btn btn-primary">
                        {{ "beer.add.measurement"|trans }}
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        {% for measurement in beer.measurements %}
            var ctx = $('#mChart_{{ measurement.id }}');
            charts[{{ measurement.id }}] = new Chart(ctx, defoultChart);
        {% endfor %}

        $( document ).ready(function () {
            initMeasurementCharts({{ beer.id }});
            var t = setInterval(function () {
                initMeasurementCharts({{ beer.id }});
            }, 5000);
        });

    </script>
{% endblock %}